@startuml

package "Country" {
places - [Accept(visitor)]
[Elements]
}

package "City" {
city - [Accept]
[Accept(visitor)] --> [Accept]:visitor
[SightsToSee()]
}

package "Village" {
village - [Accept(v)]
[Accept(visitor)] --> [Accept(v)]:visitor
[VillageToDo()]
}

package "Visitor" {
[Accept] --> Visitor
[Accept(v)] --> Visitor
[VisitCity] --> [SightsToSee()]
[VisitVillage] --> [VillageToDo()]
people -- [VisitCity]
people --[VisitVillage]
}

@enduml
