@startuml



package "Client" {
}

package "Country" {
Client -- Country
places - [Accept()]
[cities]
}

package "City" {
city - [Accept]
[Accept()] --> [Accept]
[SightsToSee()]
}

package "Visitor" {
Client -- Visitor
[Accept] --> Visitor:visitor
[VisitCity] --> [SightsToSee()]
people -- [VisitCity]
}

@enduml
