@startuml
Country -> City:accept(visior)
activate City #FFBBBB
Country -> Village:accept(vistor)
activate Village #FFBBBB
City -> Visitor:VisitCity
activate Visitor
Village -> Visitor:VisitVillage
Visitor -> City:SightsToSee()
activate City #DarkSalmon
Visitor -> Village:VillageToDo()
activate Village  #DarkSalmon

@enduml
